version: '3'
services:

    apache:
        build: .docker/apache
        container_name: sf_apache_si
        ports:
          - 8000:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./app:/home/wwwroot/sf
        depends_on:
          - php

    mysql:
        image: mysql
        ports:
          - 3307:3306
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf_mysql_si
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf
            MYSQL_USER: sf
            MYSQL_PASSWORD: sf

    php:
        build: .docker/php
        container_name: sf_php_si
        volumes:
          - ./app:/home/wwwroot/sf
        environment:
          - maildev_host=sf_maildev_si
        depends_on:
          - maildev
          - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf_maildev_si
        ports:
          - 8001:80
